CXX ?= g++
CXXFLAGS ?= -std=c++20 -O3 -march=native -DNDEBUG -Wall -Wextra -Wpedantic
CPPFLAGS ?= -Iinclude
LDFLAGS ?=

TARGET := benchmark
CLANG_TARGET := benchmark-clang

BENCHMARK_SOURCE := benchmarks/benchmark.cpp
SOURCES := $(sort $(wildcard src/jessesort_*.cpp))

OBJECTS := $(SOURCES:.cpp=.o) benchmarks/benchmark.o
CLANG_OBJECTS := $(SOURCES:.cpp=.clang.o) benchmarks/benchmark.clang.o

HEADERS := $(sort $(wildcard include/jessesort/jessesort_*.h)) include/jessesort/tiny_sort.h

CLANG_CXX := clang++
CLANG_CXXFLAGS := $(CXXFLAGS) -stdlib=libc++
CLANG_LDFLAGS := $(LDFLAGS) -stdlib=libc++

.PHONY: all clang run run500 run-all run-clang run500-clang run-all-clang \
        bench200 bench500 bench1000 \
        bench200-clang bench500-clang bench1000-clang \
        smoke smoke-clang clean clean-results

all: $(TARGET)

clang: $(CLANG_TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@

$(CLANG_TARGET): $(CLANG_OBJECTS)
	$(CLANG_CXX) $(CLANG_OBJECTS) $(CLANG_LDFLAGS) -o $@

src/%.o: src/%.cpp $(HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

benchmarks/benchmark.o: $(BENCHMARK_SOURCE) $(HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

src/%.clang.o: src/%.cpp $(HEADERS)
	$(CLANG_CXX) $(CPPFLAGS) $(CLANG_CXXFLAGS) -c $< -o $@

benchmarks/benchmark.clang.o: $(BENCHMARK_SOURCE) $(HEADERS)
	$(CLANG_CXX) $(CPPFLAGS) $(CLANG_CXXFLAGS) -c $< -o $@

# Default benchmark: six E229 representative variations + std::sort; 500 paired
# trials at 1k/10k/100k and 50 at 1m. The 12 historical baseline inputs plus the
# two E228 mixed-phase router-safety inputs are generated by benchmark.cpp.
run run500 bench500: $(TARGET)
	./$(TARGET) 500 all 2

# Explicit all-variation sweep. This is intentionally not the routine default.
run-all: $(TARGET)
	./$(TARGET) 500 all 2 "" all

run-clang run500-clang bench500-clang: $(CLANG_TARGET)
	./$(CLANG_TARGET) 500 all 2

run-all-clang: $(CLANG_TARGET)
	./$(CLANG_TARGET) 500 all 2 "" all

# Faster/larger sweeps retain the same 10:1 reduction at 1m.
bench200: $(TARGET)
	./$(TARGET) 200 all 2

bench1000: $(TARGET)
	./$(TARGET) 1000 all 2

bench200-clang: $(CLANG_TARGET)
	./$(CLANG_TARGET) 200 all 2

bench1000-clang: $(CLANG_TARGET)
	./$(CLANG_TARGET) 1000 all 2

# Quick correctness/build checks; not suitable for performance conclusions.
smoke: $(TARGET)
	./$(TARGET) 2 10000 1

smoke-clang: $(CLANG_TARGET)
	./$(CLANG_TARGET) 2 10000 1

clean:
	rm -f $(TARGET) $(CLANG_TARGET) \
	      src/*.o benchmarks/*.o \
	      src/*.clang.o benchmarks/*.clang.o \
	      *.out *.exe

# Benchmark artifacts are deliberately ephemeral and never used as future inputs.
clean-results:
	rm -rf results
